### PR TITLE
Update azure.yaml template name metadata

### PR DESCRIPTION
**Pull request by kristenwomack**
## Purpose

Added the template name `azure-openai-assistant-javascript` in the `azure.yaml` to track attempted and successful deployments in telemetry.

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by glaucia86 — APPROVED** [review]
LGTM

**Comment by kristenwomack** [comment]
@anfibiacreativa will you merge this PR please?

**Review by manekinekko — APPROVED** [review]

**Comment by manekinekko** [comment]
Thank you @kristenwomack somehow I am just seeing your comment now. Sorry for the delay!

**Comment by kristenwomack** [comment]
> Thank you @kristenwomack somehow I am just seeing your comment now. Sorry for the delay!

Thank you!

**Pull request merged**
